name: waste_mx
description: WasteMX is a waste management app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.5.3+1
  scoped_model: "^1.0.1"
  http: "^0.12.0+1"
  mime: ^0.9.6+2
  shared_preferences: ^0.5.2
  geolocator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/facebook.png
  - assets/google.png
  - assets/twitter.png
  - assets/waste_home.jpg
  - assets/dispose.jpg
  - assets/profile.png
  - assets/obd-1.png
  - assets/obd-2.png
  - assets/obd-3.png
  - assets/obd-4.png
  - assets/logo.png
  - assets/welcome-img.png
  - assets/success.png
  - assets/fail.png
  - assets/organic.png
  - assets/intro.png
  - assets/recycling-bin.png
  - assets/eco-factory.png
  - assets/target.png
  - assets/sewage.png
  - assets/analysis.png
  - assets/creative.png
  - assets/garbage-can.png
  - assets/house.png
  - assets/industrial.png
  - assets/harvest.png
  - assets/bulk.png
  - assets/nuclear-plant.png
  - assets/throw-to-paper-bin.png
  - assets/wallet-enclosed.png
  - assets/wallet.png
  - assets/clean_bin_angle.png
  - assets/eco-factory-solid.png
  - assets/glass.png
  - assets/incineration.png
  - assets/stacked-print-products.png
  - assets/plastic-bottle.png
  - assets/thick-magnet.png
  - assets/no-network.png
  - assets/decluster/vehicles.png
  - assets/decluster/bottles.png
  - assets/decluster/clothes.png
  - assets/decluster/appliances.png
  - assets/decluster/furniture.png
  - assets/decluster/household.png
  - assets/decluster/stationery.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Regular.ttf
  - family: Lato
    fonts:
    - asset: assets/fonts/Lato-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
